### ISSUE TITLE
auth Phone

### ISSUE THREAD

**Issue by blondie63** [HathTech/flutterfire#1]
I've tested Sign in with Phone but all numbers are not valid..
is this a Sign in or Sign Up ?

**Comment by HathTech** [comment]
Hey the format  is +919852954321 
Like +countrycode and then number

**Comment by blondie63** [comment]
look..
<img width="293" alt="flutter-dev-phone-fail" src="https://user-images.githubusercontent.com/1261851/71735278-5238c380-2e4e-11ea-9de1-93d02bf4c932.png">

where is Firebase settings ?

**Comment by HathTech** [comment]
Sorry. I thought each country number is 10 digits long. You can change the regex here lib/utils/validators.dart 
Phone validation. 

You can follow documentation on YouTube to setup firebase. 
https://youtu.be/KfQxmb_tE_s

**Comment by blondie63** [comment]
this is better regex:

  static final RegExp _phoneRegex = RegExp(
    r'(([+][(]?[0-9]{1,3}[)]?)|([(]?[0-9]{4}[)]?))\s*[)]?[-\s\.]?[(]?[0-9]{1,3}[)]?([-\s\.]?[0-9]{3})([-\s\.]?[0-9]{3,4})$',
  );

**Comment by HathTech** [comment]
Noted! 
Will change in future updates. 
Thank you
